//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBENHNHAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BACSI()
        {
            this.CHITIETBENHANs = new HashSet<CHITIETBENHAN>();
        }
    
        public string MABS { get; set; }
        public string HOTEN { get; set; }
        public string SODIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string GIOITINH { get; set; }
        public string GIOITHIEU { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string idK { get; set; }
        public string idTK { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBENHAN> CHITIETBENHANs { get; set; }
    }
}
