//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBENHNHAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBENHAN
    {
        public string MABA { get; set; }
        public string idBS { get; set; }
        public string idBN { get; set; }
        public string TENBENHAN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<System.TimeSpan> GIO { get; set; }
        public Nullable<int> MACH { get; set; }
        public Nullable<int> THANNHIET { get; set; }
        public Nullable<int> NHIPTHO { get; set; }
        public Nullable<int> CHIEUCAO { get; set; }
        public Nullable<int> CANNANG { get; set; }
        public string MATTRAI { get; set; }
        public string MATPHAI { get; set; }
        public Nullable<int> NHANAPPHAI { get; set; }
        public Nullable<int> NHANAPTRAI { get; set; }
        public string CHUANDOANLAMSANG { get; set; }
        public string CHUANDOANCUOICUNG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string TRANGTHAI { get; set; }
        public string TIENSUBENH { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual BENHNHAN BENHNHAN { get; set; }
    }
}
