//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBENHNHAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOCPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUOCPHAM()
        {
            this.CHITIETDUOCPHAMs = new HashSet<CHITIETDUOCPHAM>();
        }
    
        public string MADP { get; set; }
        public string idLDP { get; set; }
        public string TENDUOCPHAM { get; set; }
        public string MOTA { get; set; }
        public string XUATXU { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDUOCPHAM> CHITIETDUOCPHAMs { get; set; }
        public virtual LOAIDUOCPHAM LOAIDUOCPHAM { get; set; }
    }
}
