//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBENHNHAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public string idBN { get; set; }
        public string TENHOADON { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string CHITIETHOADON { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
    }
}
