//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBENHNHAN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDULIEUBENHNHANEntities : DbContext
    {
        public QLDULIEUBENHNHANEntities()
            : base("name=QLDULIEUBENHNHANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BACSI> BACSIs { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<CHITIETBENHAN> CHITIETBENHANs { get; set; }
        public virtual DbSet<CHITIETDUOCPHAM> CHITIETDUOCPHAMs { get; set; }
        public virtual DbSet<CHITIETTHIETBI> CHITIETTHIETBIs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LOAIDUOCPHAM> LOAIDUOCPHAMs { get; set; }
        public virtual DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public virtual DbSet<LOAITHIETBI> LOAITHIETBIs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
        public virtual DbSet<PHIEUHEN> PHIEUHENs { get; set; }
        public virtual DbSet<DUOCPHAM> DUOCPHAMs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<DONTHUOC> DONTHUOCs { get; set; }
        public virtual DbSet<BAOCAO> BAOCAOs { get; set; }
    }
}
